const Article = () => {
  return (
    <div className="flex p-4 flex-col max-w-xl">
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quam id leo in vitae turpis massa sed elementum. Eu tincidunt tortor aliquam nulla. Enim facilisis gravida neque convallis a cras semper auctor. Rhoncus dolor purus non enim praesent. Lorem sed risus ultricies tristique nulla. Accumsan sit amet nulla facilisi morbi tempus iaculis. Ut morbi tincidunt augue interdum velit. Mauris vitae ultricies leo integer. Varius quam quisque id diam vel quam elementum pulvinar. Ac orci phasellus egestas tellus rutrum. Sit amet purus gravida quis blandit turpis. Rutrum tellus pellentesque eu tincidunt tortor aliquam nulla facilisi. Et malesuada fames ac turpis egestas. Ullamcorper a lacus vestibulum sed arcu non odio euismod lacinia. Imperdiet nulla malesuada pellentesque elit eget. Pellentesque sit amet porttitor eget dolor morbi non arcu risus. Porttitor massa id neque aliquam. Molestie nunc non blandit massa enim.</p>

      <p>Viverra justo nec ultrices dui. Vel fringilla est ullamcorper eget nulla facilisi. Adipiscing elit pellentesque habitant morbi tristique senectus et. Pellentesque habitant morbi tristique senectus et netus et. A arcu cursus vitae congue mauris rhoncus aenean. Integer quis auctor elit sed vulputate mi. Massa massa ultricies mi quis hendrerit. Massa vitae tortor condimentum lacinia quis. Gravida neque convallis a cras. Libero nunc consequat interdum varius sit amet mattis. Interdum consectetur libero id faucibus. Id volutpat lacus laoreet non curabitur gravida. Lacus luctus accumsan tortor posuere ac ut consequat semper. Facilisi nullam vehicula ipsum a arcu. Faucibus pulvinar elementum integer enim neque volutpat ac. Quis risus sed vulputate odio ut enim blandit volutpat maecenas. Aliquam ultrices sagittis orci a scelerisque purus semper eget. Posuere ac ut consequat semper viverra nam libero justo. Vestibulum lorem sed risus ultricies tristique nulla. Sed elementum tempus egestas sed sed risus pretium quam vulputate.</p>

      <p>Egestas tellus rutrum tellus pellentesque eu. Velit laoreet id donec ultrices tincidunt arcu. Vitae suscipit tellus mauris a diam maecenas. Proin sed libero enim sed faucibus turpis in eu. In ornare quam viverra orci sagittis eu volutpat odio facilisis. Tellus integer feugiat scelerisque varius morbi enim nunc faucibus a. Eget nulla facilisi etiam dignissim diam quis. Sagittis aliquam malesuada bibendum arcu vitae. Consequat mauris nunc congue nisi vitae suscipit tellus. Varius vel pharetra vel turpis nunc eget lorem dolor. Ut sem nulla pharetra diam sit amet. Dignissim diam quis enim lobortis scelerisque fermentum dui faucibus. Ipsum dolor sit amet consectetur adipiscing elit ut aliquam. Pharetra vel turpis nunc eget lorem. Vitae turpis massa sed elementum tempus egestas. Sed lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt. Sem fringilla ut morbi tincidunt augue interdum velit euismod. Arcu ac tortor dignissim convallis aenean et tortor at risus. Habitant morbi tristique senectus et. Pellentesque diam volutpat commodo sed egestas egestas fringilla phasellus faucibus.</p>

      <p>Cum sociis natoque penatibus et magnis. Eu volutpat odio facilisis mauris sit. Aenean euismod elementum nisi quis eleifend quam. Aliquet nec ullamcorper sit amet. Scelerisque viverra mauris in aliquam sem fringilla ut morbi. Et ultrices neque ornare aenean euismod elementum nisi quis eleifend. Cras adipiscing enim eu turpis egestas pretium aenean pharetra. Aliquam sem fringilla ut morbi tincidunt. Congue nisi vitae suscipit tellus. Nisl suscipit adipiscing bibendum est. Erat pellentesque adipiscing commodo elit at imperdiet dui accumsan. Enim praesent elementum facilisis leo vel fringilla est. Quam vulputate dignissim suspendisse in est ante. Donec massa sapien faucibus et molestie ac feugiat sed lectus. Sed felis eget velit aliquet sagittis id consectetur purus ut. Dui accumsan sit amet nulla facilisi morbi tempus iaculis. Tempus iaculis urna id volutpat lacus laoreet non curabitur gravida. Feugiat vivamus at augue eget arcu dictum varius duis. Interdum velit laoreet id donec ultrices tincidunt arcu non sodales. Congue mauris rhoncus aenean vel elit scelerisque.</p>

      <p>Eu sem integer vitae justo. At auctor urna nunc id cursus. Scelerisque eu ultrices vitae auctor eu augue ut. Tortor aliquam nulla facilisi cras fermentum odio eu feugiat pretium. In ornare quam viverra orci sagittis. Quam vulputate dignissim suspendisse in est ante in nibh. Nunc sed blandit libero volutpat sed cras ornare arcu dui. Nibh nisl condimentum id venenatis. Quam viverra orci sagittis eu. Urna nunc id cursus metus aliquam eleifend.</p>
    </div>
  )
}
export default Article